'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from './AuthContext';
import { supabase } from '@/lib/supabase';

export type LanguageCode = 'English' | 'Spanish' | 'French' | 'German' | 'Chinese' | 'Japanese' | 'Arabic' | 'Portuguese' | 'Turkish' | 'Russian' | 'Hindi' | 'Vietnamese';

const translations: Record<LanguageCode, Record<string, string>> = {
    English: {
        home: 'Home',
        start: 'Start',
        record: 'Record',
        dashboard: 'Dashboard',
        welcome: 'Welcome back',
        welcome_back: 'Welcome back',
        wallet: 'Wallet',
        vip_map: 'Vip map',
        profile: 'Profile',
        support: 'Support',
        logout: 'Sign out',
        sign_out: 'Sign out',
        settings: 'Settings',
        language: 'Language',
        currency: 'Currency',
        dark_mode: 'Dark mode',
        notifications: 'Notifications',
        account_security: 'Account & security',
        email_address: 'Email address',
        change_password: 'Change password',
        my_information: 'My information',
        employee_id: 'Employee ID',
        wallet_address: 'Wallet address',
        bind_email: 'Bind e-mail',
        security_hub: 'Security hub',
        security_center: 'Security center',
        manage_account_identity: 'Manage account identity',
        available_balance: 'Available balance',
        balance: 'Available balance',
        balance_sidebar: 'Balance',
        available_tether: 'Available tether (USDT)',
        secured_rebate: 'Secured rebate',
        today_profit: "Today's profit",
        total_profit: 'Total profit',
        daily_profit: 'Daily profit',
        frozen_asset: 'Frozen asset',
        escrow_hold: 'Escrow hold',
        total_assets: 'Total assets',
        wallet_overview: 'Wallet overview',
        tasks: 'Tasks',
        task: 'Task',
        all: 'All',
        pending: 'Pending',
        completed: 'Completed',
        cancelled: 'Cancelled',
        status: 'Status',
        timestamp: 'Timestamp',
        task_type: 'Task type',
        amount_earned: 'Amount earned',
        total_records_found: 'Total records found',
        no_records_found: 'No matching records found',
        item_not_found: 'Item not found',
        matching: 'Matching...',
        sequence: 'Sequence',
        tap_to_match: 'Tap to match',
        neural_active: 'Neural active',
        match_found: 'Match found!',
        connecting_to_cloud: 'Connecting to cloud...',
        analyzing_market: 'Analyzing market...',
        identifying_optimal_match: 'Identifying optimal match...',
        finalizing_allocation: 'Finalizing allocation...',
        optimization_hub_active: 'Task hub active',
        ready_to_match: 'Ready to match',
        deposit: 'Deposit',
        withdraw: 'Withdraw',
        recharge: 'Recharge',
        recharge_now: 'Recharge now',
        secure_payout: 'Secure payout',
        settlement_amount: 'Settlement amount',
        total_commissions: 'Total commissions',
        task_submitted: 'Task submitted',
        settlement_portal: 'Settlement portal',
        employee_levels: 'Employee levels',
        vip_experience: 'VIP experience',
        locked: 'Locked',
        set_progress: 'Set progress',
        daily_limit_reached: 'Daily limit reached',
        set_complete_contact_support: 'Set {set} complete • Contact support',
        commission_earned: 'Commission earned',
        commission_rate: 'Comm. rate',
        about_us: 'About us',
        important_notes: 'Important notes',
        working_hours_note: 'Hours of operation (Eastern Time): 09:00 AM - 09:00 PM. If you have any questions, please contact the Concierge Desk via the Support button on the home page.',
        deposit_description: 'Add funds to your account',
        withdraw_description: 'Request earnings payout',
        start_tasks_desc: 'Match tasks and earn commission',
        my_records_desc: 'View task history and earnings',
        my_profile_desc: 'Account settings and information',
        faq_desc: 'Frequently asked questions',
        rules_desc: 'System governance and rewards',
        platform_architecture_guide: 'Platform architecture guide',
        compliance_framework: 'Compliance framework',
        referral_program: 'Referral program',
        total_referrals: 'Total referrals',
        invite_friends: 'Invite friends',
        copy_link: 'Copy link',
        view_more: 'View more',
        click_to_optimize_now: 'Click to start task now',
        view_recent_settlements: 'View recent settlements',
        start_tasks: 'Start tasks',
        activity_records: 'Record',
        my_profile: 'My profile',
        faq: 'Faq',
        legal_governance: 'Legal governance',
        institutional: 'Institutional',
        system_restricted: 'System restricted',
        negative_balance_detected: 'Negative balance detected',
        live_support: 'Live support',
        joined: 'Joined',
        submitting: 'Submitting...',
        submitting_order: 'Submitting order...',
        submit_order: 'Submit order',
        task_profit: 'Task profit',
        referral_bonus: 'Referral bonus'
    },
    Spanish: {
        home: 'Inicio',
        start: 'Comenzar',
        record: 'Registro',
        dashboard: 'Tablero',
        welcome: 'Bienvenido de nuevo',
        welcome_back: 'Bienvenido de nuevo',
        wallet: 'Billetera',
        vip_map: 'Mapa Vip',
        profile: 'Perfil',
        support: 'Soporte',
        logout: 'Cerrar sesión',
        sign_out: 'Cerrar sesión',
        settings: 'Ajustes',
        language: 'Idioma',
        currency: 'Moneda',
        dark_mode: 'Modo oscuro',
        notifications: 'Notificaciones',
        account_security: 'Cuenta y seguridad',
        email_address: 'Correo electrónico',
        change_password: 'Cambiar contraseña',
        my_information: 'Mi información',
        employee_id: 'ID de Empleado',
        wallet_address: 'Dirección de billetera',
        bind_email: 'Vincular correo',
        security_hub: 'Centro de seguridad',
        security_center: 'Centro de seguridad',
        manage_account_identity: 'Gestionar identidad de cuenta',
        available_balance: 'Saldo disponible',
        balance: 'Saldo disponible',
        balance_sidebar: 'Saldo',
        available_tether: 'Tether disponible (USDT)',
        secured_rebate: 'Reembolso asegurado',
        today_profit: 'Ganancia de hoy',
        total_profit: 'Ganancia total',
        daily_profit: 'Ganancia diaria',
        frozen_asset: 'Activo congelado',
        escrow_hold: 'Retención de escrow',
        total_assets: 'Activos totales',
        wallet_overview: 'Resumen de billetera',
        tasks: 'Tareas',
        task: 'Tarea',
        all: 'Todo',
        pending: 'Pendiente',
        completed: 'Completado',
        cancelled: 'Cancelado',
        status: 'Estado',
        timestamp: 'Marca de tiempo',
        task_type: 'Tipo de tarea',
        amount_earned: 'Monto ganado',
        total_records_found: 'Total de registros encontrados',
        search_tasks: 'Buscar tareas...',
        no_records_found: 'No se encontraron registros',
        item_not_found: 'Elemento no encontrado',
        matching: 'Emparejando...',
        sequence: 'SECUENCIA',
        tap_to_match: 'Tocar para emparejar',
        neural_active: 'Neural activo',
        match_found: '¡Pareja encontrada!',
        connecting_to_cloud: 'Conectando a la nube...',
        analyzing_market: 'Analizando mercado...',
        identifying_optimal_match: 'Identificando pareja óptima...',
        finalizing_allocation: 'Finalizando asignación...',
        optimization_hub_active: 'Centro de tareas activo',
        ready_to_match: 'Listo para emparejar',
        deposit: 'Depositar',
        withdraw: 'Retirar',
        recharge: 'Recargar',
        recharge_now: 'Recargar ahora',
        secure_payout: 'Pago seguro',
        settlement_amount: 'Monto de liquidación',
        total_commissions: 'Comisiones totales',
        task_submitted: 'Tarea enviada',
        settlement_portal: 'Portal de liquidación',
        employee_levels: 'Niveles de empleado',
        vip_experience: 'Experiencia VIP',
        locked: 'Bloqueado',
        set_progress: 'Progreso del set',
        daily_limit_reached: 'Límite diario alcanzado',
        set_complete_contact_support: 'Set {set} completo • Contactar soporte',
        commission_earned: 'Comisión ganada',
        commission_rate: 'Tasa de com.',
        about_us: 'Sobre nosotros',
        important_notes: 'Notas importantes',
        working_hours_note: 'Horario de operación (Hora del Este): 09:00 AM - 09:00 PM. Si tiene alguna pregunta, comuníquese con el Concierge a través del botón de Soporte.',
        deposit_description: 'Añadir fondos a su cuenta',
        withdraw_description: 'Solicitar pago de ganancias',
        start_tasks_desc: 'Emparejar tareas y ganar comisión',
        my_records_desc: 'Ver historial de tareas y ganancias',
        my_profile_desc: 'Ajustes e información de la cuenta',
        faq_desc: 'Preguntas frecuentes',
        rules_desc: 'Gobernanza del sistema y recompensas',
        platform_architecture_guide: 'Guía de arquitectura de la plataforma',
        compliance_framework: 'Marco de cumplimiento',
        referral_program: 'Programa de referidos',
        total_referrals: 'Total de referidos',
        invite_friends: 'Invitar amigos',
        copy_link: 'Copiar enlace',
        view_more: 'Ver más',
        click_to_optimize_now: 'Haz clic para empezar tarea',
        view_recent_settlements: 'Ver liquidaciones recientes',
        start_tasks: 'Iniciar tareas',
        activity_records: 'Registros',
        my_profile: 'Mi perfil',
        faq: 'Preguntas frecuentes',
        legal_governance: 'Gobernanza legal',
        institutional: 'Institucional',
        system_restricted: 'Sistema restringido',
        negative_balance_detected: 'Saldo negativo detectado',
        live_support: 'Soporte en vivo',
        joined: 'Unido',
        submitting: 'Enviando...',
        submitting_order: 'Enviando orden...',
        submit_order: 'Enviar orden',
        task_profit: 'Ganancia de tarea',
        referral_bonus: 'Bono de referido'
    },
    French: {
        home: 'Accueil',
        start: 'Commencer',
        record: 'Enregistrer',
        dashboard: 'Tableau de bord',
        welcome: 'Bon retour',
        welcome_back: 'Bon retour',
        wallet: 'Portefeuille',
        vip_map: 'Carte Vip',
        profile: 'Profil',
        support: 'Support',
        logout: 'Déconnexion',
        sign_out: 'Déconnexion',
        settings: 'Paramètres',
        language: 'Langue',
        currency: 'Devise',
        dark_mode: 'Mode sombre',
        notifications: 'Notifications',
        account_security: 'Compte et sécurité',
        email_address: 'Adresse e-mail',
        change_password: 'Modifier le mot de passe',
        my_information: 'Mes informations',
        employee_id: 'ID employé',
        wallet_address: 'Adresse du portefeuille',
        bind_email: 'Lier l’e-mail',
        security_hub: 'Centre de sécurité',
        security_center: 'Centre de sécurité',
        manage_account_identity: 'Gérer l’identité du compte',
        available_balance: 'Solde disponible',
        balance: 'Solde disponible',
        balance_sidebar: 'Solde',
        available_tether: 'Tether disponible (USDT)',
        secured_rebate: 'Remise sécurisée',
        today_profit: 'Bénéfice d’aujourd’hui',
        total_profit: 'Bénéfice total',
        daily_profit: 'Bénéfice quotidien',
        frozen_asset: 'Actif gelé',
        escrow_hold: 'Retenue en séquestre',
        total_assets: 'Total des actifs',
        wallet_overview: 'Aperçu du portefeuille',
        tasks: 'Tâches',
        task: 'Tâche',
        all: 'Tout',
        pending: 'En attente',
        completed: 'Terminé',
        cancelled: 'Annulé',
        status: 'Statut',
        timestamp: 'Horodatage',
        task_type: 'Type de tâche',
        amount_earned: 'Montant gagné',
        total_records_found: 'Total des dossiers trouvés',
        no_records_found: 'Aucun dossier correspondant trouvé',
        item_not_found: 'Élément non trouvé',
        matching: 'Correspondance...',
        sequence: 'SÉQUENCE',
        tap_to_match: 'Appuyer pour correspondre',
        neural_active: 'Neural actif',
        match_found: 'Match trouvé !',
        connecting_to_cloud: 'Connexion au cloud...',
        analyzing_market: 'Analyse du marché...',
        identifying_optimal_match: 'Identification du match optimal...',
        finalizing_allocation: 'Finalisation de l’allocation...',
        optimization_hub_active: 'Centre de tâches actif',
        ready_to_match: 'Prêt à correspondre',
        deposit: 'Dépôt',
        withdraw: 'Retirer',
        recharge: 'Recharger',
        recharge_now: 'Recharger maintenant',
        secure_payout: 'Paiement sécurisé',
        settlement_amount: 'Montant du règlement',
        total_commissions: 'Commissions totales',
        task_submitted: 'Tâche soumise',
        settlement_portal: 'Portail de règlement',
        employee_levels: 'Niveaux des employés',
        vip_experience: 'Expérience VIP',
        locked: 'Verrouillé',
        set_progress: 'Progression de la série',
        daily_limit_reached: 'Limite quotidienne atteinte',
        set_complete_contact_support: 'Série {set} terminée • Contactez le support',
        commission_earned: 'Commission gagnée',
        commission_rate: 'Taux de comm.',
        about_us: 'À propos de nous',
        important_notes: 'Notes importantes',
        working_hours_note: 'Heures d’ouverture (heure de l’Est) : 09h00 - 21h00. Si vous avez des questions, veuillez contacter le service Conciergerie via le bouton Support.',
        deposit_description: 'Ajouter des fonds à votre compte',
        withdraw_description: 'Demander le paiement des gains',
        start_tasks_desc: 'Faire correspondre les tâches et gagner des commissions',
        my_records_desc: 'Afficher l’historique des tâches et les gains',
        my_profile_desc: 'Paramètres et informations du compte',
        faq_desc: 'Questions fréquemment posées',
        rules_desc: 'Gouvernance du système et récompenses',
        platform_architecture_guide: 'Guide d’architecture de la plateforme',
        compliance_framework: 'Cadre de conformité',
        referral_program: 'Programme de parrainage',
        total_referrals: 'Total des parrainages',
        invite_friends: 'Inviter des amis',
        copy_link: 'Copier le lien',
        view_more: 'Voir plus',
        click_to_optimize_now: 'Cliquez pour optimiser maintenant',
        view_recent_settlements: 'Afficher les règlements récents',
        start_tasks: 'Démarrer les tâches',
        activity_records: 'Dossiers',
        my_profile: 'Mon profil',
        faq: 'FAQ',
        legal_governance: 'Gouvernance légale',
        institutional: 'Institutionnel',
        system_restricted: 'Système restreint',
        negative_balance_detected: 'Solde négatif détecté',
        live_support: 'Support en direct',
        joined: 'Rejoint',
        submitting: 'Envoi...',
        submitting_order: 'Envoi de la commande...',
        submit_order: 'Soumettre la commande',
        task_profit: 'Profit de tâche',
        referral_bonus: 'Bonus de parrainage'
    },
    German: {
        home: 'Startseite',
        start: 'Starten',
        record: 'Aufzeichnung',
        dashboard: 'Dashboard',
        welcome: 'Willkommen zurück',
        welcome_back: 'Willkommen zurück',
        wallet: 'Brieftasche',
        vip_map: 'Vip karte',
        profile: 'Profil',
        support: 'Unterstützung',
        logout: 'Abmelden',
        sign_out: 'Abmelden',
        settings: 'Einstellungen',
        language: 'Sprache',
        currency: 'Währung',
        dark_mode: 'Dunkelmodus',
        notifications: 'Benachrichtigungen',
        account_security: 'Konto & sicherheit',
        email_address: 'E-mail-adresse',
        change_password: 'Passwort ändern',
        my_information: 'Meine informationen',
        employee_id: 'Mitarbeiter-ID',
        wallet_address: 'Wallet-adresse',
        bind_email: 'E-mail binden',
        security_hub: 'Sicherheitszentrum',
        security_center: 'Sicherheitszentrum',
        manage_account_identity: 'Kontonidentität verwalten',
        available_balance: 'Verfügbares guthaben',
        balance: 'Verfügbares guthaben',
        balance_sidebar: 'Guthaben',
        available_tether: 'Verfügbares tether (USDT)',
        secured_rebate: 'Gesichertes rabatt',
        today_profit: 'Heutiger gewinn',
        total_profit: 'Gesamtgewinn',
        daily_profit: 'Täglicher gewinn',
        frozen_asset: 'Gefrorener vermögenswert',
        escrow_hold: 'Treuhand-sperre',
        total_assets: 'Gesamtvermögen',
        wallet_overview: 'Wallet-übersicht',
        tasks: 'Aufgaben',
        task: 'Aufgabe',
        all: 'Alle',
        pending: 'Ausstehend',
        completed: 'Abgeschlossen',
        cancelled: 'Storniert',
        status: 'Status',
        timestamp: 'Zeitstempel',
        task_type: 'Aufgabentyp',
        amount_earned: 'Verdienter betrag',
        total_records_found: 'Insgesamt gefundene datensätze',
        no_records_found: 'Keine passenden datensätze gefunden',
        item_not_found: 'Element nicht gefunden',
        matching: 'Abgleichen...',
        sequence: 'SEQUENZ',
        tap_to_match: 'Zum abgleichen tippen',
        neural_active: 'Neural aktiv',
        match_found: 'Treffer gefunden!',
        connecting_to_cloud: 'Verbindung zur cloud wird hergestellt...',
        analyzing_market: 'Marktanalyse...',
        identifying_optimal_match: 'Optimalen treffer identifizieren...',
        finalizing_allocation: 'Zuweisung abschließen...',
        optimization_hub_active: 'Aufgaben-Hub aktiv',
        ready_to_match: 'Bereit zum abgleichen',
        deposit: 'Einzahlung',
        withdraw: 'Auszahlen',
        recharge: 'Aufladen',
        recharge_now: 'Jetzt aufladen',
        secure_payout: 'Sichere auszahlung',
        settlement_amount: 'Abrechnungsbetrag',
        total_commissions: 'Gesamtprovisionen',
        task_submitted: 'Aufgabe eingereicht',
        settlement_portal: 'Abrechnungsportal',
        employee_levels: 'Mitarbeiterstufen',
        vip_experience: 'VIP-erfahrung',
        locked: 'Gesperrt',
        set_progress: 'Satz-fortschritt',
        daily_limit_reached: 'Tägliches limit erreicht',
        set_complete_contact_support: 'Satz {set} abgeschlossen • Support kontaktieren',
        commission_earned: 'Provision verdient',
        commission_rate: 'Prov.-rate',
        about_us: 'Über uns',
        important_notes: 'Wichtige hinweise',
        working_hours_note: 'Betriebszeiten (EST): 09:00 - 21:00 Uhr. Bei fragen wenden Sie sich bitte über die Support-schaltfläche an den Concierge desk.',
        deposit_description: 'Guthaben zu Ihrem konto hinzufügen',
        withdraw_description: 'Auszahlung von gewinnen anfordern',
        start_tasks_desc: 'Aufgaben abgleichen und provision verdienen',
        my_records_desc: 'Aufgabenverlauf und gewinne anzeigen',
        my_profile_desc: 'Kontoeinstellungen und informationen',
        faq_desc: 'Häufig gestellte fragen',
        rules_desc: 'System-governance und belohnungen',
        platform_architecture_guide: 'Plattform-architektur-leitfaden',
        compliance_framework: 'Compliance-rahmen',
        referral_program: 'Empfehlungsprogramm',
        total_referrals: 'Empfehlungen insgesamt',
        invite_friends: 'Freunde einladen',
        copy_link: 'Link kopieren',
        view_more: 'Mehr anzeigen',
        click_to_optimize_now: 'Klicken Sie, um jetzt zu optimieren',
        view_recent_settlements: 'Aktuelle abrechnungen anzeigen',
        start_tasks: 'Aufgaben starten',
        activity_records: 'Aufzeichnungen',
        my_profile: 'Mein profil',
        faq: 'FAQ',
        legal_governance: 'Rechtliche governance',
        institutional: 'Institutionell',
        system_restricted: 'System eingeschränkt',
        negative_balance_detected: 'Negativer saldo erkannt',
        live_support: 'Live-unterstützung',
        joined: 'Beigetreten',
        submitting: 'Wird gesendet...',
        submitting_order: 'Bestellung wird gesendet...',
        submit_order: 'Bestellung absenden',
        task_profit: 'Aufgabengewinn',
        referral_bonus: 'Empfehlungsbonus'
    },
    Chinese: {
        home: '首页',
        start: '开始',
        record: '记录',
        dashboard: '控制面板',
        welcome: '欢迎回来',
        welcome_back: '欢迎回来',
        wallet: '钱包',
        vip_map: 'Vip 地图',
        profile: '个人资料',
        support: '在线客服',
        logout: '退出登录',
        sign_out: '退出登录',
        settings: '设置',
        language: '语言',
        currency: '货币',
        dark_mode: '深色模式',
        notifications: '通知设置',
        account_security: '账户与安全',
        email_address: '电子邮箱',
        change_password: '修改密码',
        my_information: '个人信息',
        employee_id: '员工 ID',
        wallet_address: '钱包地址',
        bind_email: '绑定邮箱',
        security_hub: '安全中心',
        security_center: '安全中心',
        manage_account_identity: '管理账户身份',
        available_balance: '可用余额',
        balance: '可用余额',
        balance_sidebar: '账户余额',
        available_tether: '可用 Tether (USDT)',
        secured_rebate: '保障回扣',
        today_profit: '今日收益',
        total_profit: '总收益',
        daily_profit: '每日收益',
        frozen_asset: '冻结资产',
        escrow_hold: '托管持有',
        total_assets: '总资产',
        wallet_overview: '钱包概览',
        tasks: '任务',
        task: '任务',
        all: '全部',
        pending: '待处理',
        completed: '已完成',
        cancelled: '已取消',
        status: '状态',
        timestamp: '时间戳',
        task_type: '任务类型',
        amount_earned: '赚取金额',
        total_records_found: '查询记录总数',
        no_records_found: '未找到匹配记录',
        item_not_found: '未找到项目',
        matching: '匹配中...',
        sequence: '序列',
        tap_to_match: '点击开始匹配',
        neural_active: '神经网活跃',
        match_found: '匹配成功！',
        connecting_to_cloud: '连接云端...',
        analyzing_market: '分析市场...',
        identifying_optimal_match: '识别最佳匹配...',
        finalizing_allocation: '正在完成分配...',
        optimization_hub_active: '任务中心已激活',
        ready_to_match: '准备匹配',
        deposit: '充值',
        withdraw: '提现',
        recharge: '充值',
        recharge_now: '立即充值',
        secure_payout: '安全结算',
        settlement_amount: '结算金额',
        total_commissions: '总佣金',
        task_submitted: '任务已提交',
        settlement_portal: '结算门户',
        employee_levels: '员工等级',
        vip_experience: 'VIP 体验',
        locked: '已锁定',
        set_progress: '任务组进度',
        daily_limit_reached: '已达到每日任务上限',
        set_complete_contact_support: '第 {set} 组任务已完成 • 请联系客服',
        commission_earned: '已赚佣金',
        commission_rate: '佣金率',
        about_us: '关于我们',
        important_notes: '重要提示',
        working_hours_note: '营业时间（东部时间）：09:00 AM - 09:00 PM。如有任何疑问，请通过主页的客服按钮联系礼宾台。',
        deposit_description: '为您的账户充值',
        withdraw_description: '申请提取收益',
        start_tasks_desc: '匹配任务并赚取佣金',
        my_records_desc: '查看任务历史和收益',
        my_profile_desc: '账户设置和信息',
        faq_desc: '常见问题',
        rules_desc: '系统治理与奖励',
        platform_architecture_guide: '平台架构指南',
        compliance_framework: '合规框架',
        referral_program: '推荐计划',
        total_referrals: '推荐总数',
        invite_friends: '邀请朋友',
        copy_link: '复制链接',
        view_more: '查看更多',
        click_to_optimize_now: '点击立即优化',
        view_recent_settlements: '查看最近结算',
        start_tasks: '开始任务',
        activity_records: '记录',
        my_profile: '个人资料',
        faq: '常见问题',
        legal_governance: '法律监管',
        institutional: '机构',
        system_restricted: '系统受限',
        negative_balance_detected: '检测到负余额',
        live_support: '在线客服',
        joined: '加入时间',
        submitting: '提交中...',
        submitting_order: '订单提交中...',
        submit_order: '提交订单',
        task_profit: '任务收益',
        referral_bonus: '推介奖金'
    },
    Japanese: {
        home: 'ホーム',
        start: 'スタート',
        record: '記録',
        dashboard: 'ダッシュボード',
        welcome: 'おかえりなさい',
        welcome_back: 'おかえりなさい',
        wallet: 'ウォレット',
        vip_map: 'Vip マップ',
        profile: 'プロフィール',
        support: 'サポート',
        logout: 'ログアウト',
        sign_out: 'ログアウト',
        settings: '設定',
        language: '言語',
        currency: '通貨',
        dark_mode: 'ダークモード',
        notifications: '通知',
        account_security: 'アカウントとセキュリティ',
        email_address: 'メールアドレス',
        change_password: 'パスワード変更',
        my_information: 'マイ情報',
        employee_id: '従業員 ID',
        wallet_address: 'ウォレットアドレス',
        bind_email: 'メール連携',
        security_hub: 'セキュリティハブ',
        security_center: 'セキュリティセンター',
        manage_account_identity: 'アカウント ID の管理',
        available_balance: '利用可能残高',
        balance: '利用可能残高',
        balance_sidebar: '残高',
        available_tether: '利用可能な Tether (USDT)',
        secured_rebate: '保護されたリベート',
        today_profit: '今日の利益',
        total_profit: '総利益',
        daily_profit: '毎日の利益',
        frozen_asset: '凍結資産',
        escrow_hold: 'エスクロー保留',
        total_assets: '総資産',
        wallet_overview: 'ウォレットの概要',
        tasks: 'タスク',
        task: 'タスク',
        all: 'すべて',
        pending: '保留中',
        completed: '完了',
        cancelled: 'キャンセル',
        status: 'ステータス',
        timestamp: 'タイムスタンプ',
        task_type: 'タスクタイプ',
        amount_earned: '獲得金額',
        total_records_found: '見つかった総記録数',
        no_records_found: '一致する記録が見つかりません',
        item_not_found: 'アイテムが見つかりません',
        matching: 'マッチング中...',
        sequence: 'シーケンス',
        tap_to_match: 'タップしてマッチング',
        neural_active: 'ニューラルアクティブ',
        match_found: 'マッチング完了！',
        connecting_to_cloud: 'クラウドに接続中...',
        analyzing_market: '市場を分析中...',
        identifying_optimal_match: '最適なマッチを特定中...',
        finalizing_allocation: '割り当てを最終化中...',
        optimization_hub_active: 'タスクハブ動作中',
        ready_to_match: 'マッチング準備完了',
        deposit: '入金',
        withdraw: '出金',
        recharge: 'チャージ',
        recharge_now: '今すぐチャージ',
        secure_payout: '安全な支払い',
        settlement_amount: '決済金額',
        total_commissions: '总手数料',
        task_submitted: 'タスク送信済み',
        settlement_portal: '決済ポータル',
        employee_levels: '従業員レベル',
        vip_experience: 'VIP 体験',
        locked: 'ロック中',
        set_progress: 'セットの進捗',
        daily_limit_reached: '1日の制限に達しました',
        set_complete_contact_support: 'セット {set} 完了 • サポートにお問い合わせください',
        commission_earned: '獲得した手数料',
        commission_rate: '手数料率',
        about_us: '私たちについて',
        important_notes: '重要な注意事項',
        working_hours_note: '営業時間（東部標準時）：09:00 AM - 09:00 PM。ご不明な点がございましたら、ホームページのサポートボタンからコンシェルジュデスクまでお問い合わせください。',
        deposit_description: 'アカウントに残高を追加する',
        withdraw_description: '収益の出金をリクエストする',
        start_tasks_desc: 'タスクをマッチングして手数料を獲得する',
        my_records_desc: 'タスク履歴と収益を表示する',
        my_profile_desc: 'アカウント設定と情報',
        faq_desc: 'よくある質問',
        rules_desc: 'システムガバナンスと報酬',
        platform_architecture_guide: 'プラットフォームアーキテクチャガイド',
        compliance_framework: 'コンプライアンスフレームワーク',
        referral_program: '紹介プログラム',
        total_referrals: '紹介総数',
        invite_friends: '友達を招待',
        copy_link: 'リンクをコピー',
        view_more: 'もっと見る',
        click_to_optimize_now: 'クリックして今すぐ最適化',
        view_recent_settlements: '最近の決済を表示',
        start_tasks: 'タスク開始',
        activity_records: '記録',
        my_profile: 'マイプロフィール',
        faq: 'FAQ',
        legal_governance: '法的ガバナンス',
        institutional: 'インスティテューショナル',
        system_restricted: 'システム制限中',
        negative_balance_detected: 'マイナス残高が検出されました',
        live_support: 'ライブサポート',
        joined: '参加日',
        submitting: '送信中...',
        submitting_order: '注文を送信中...',
        submit_order: '注文を送信',
        task_profit: 'タスク利益',
        referral_bonus: '紹介ボーナス'
    },
    Arabic: {
        home: 'الرئيسية',
        start: 'ابدأ',
        record: 'السجل',
        dashboard: 'لوحة التحكم',
        welcome: 'مرحباً بعودتك',
        wallet: 'المحفظة',
        profile: 'الملف الشخصي',
        support: 'الدعم',
        settings: 'الإعدادات',
        language: 'اللغة',
        currency: 'العملة',
        dark_mode: 'الوضع الليلي',
        notifications: 'التنبيهات',
        deposit: 'إيداع',
        withdraw: 'سحب',
        balance: 'الرصيد المتاح',
    },
    Portuguese: {
        home: 'Início',
        start: 'Começar',
        record: 'Registro',
        dashboard: 'Painel',
        welcome: 'Bem-vindo de volta',
        wallet: 'Carteira',
        profile: 'Perfil',
        support: 'Suporte',
        settings: 'Configurações',
        language: 'Idioma',
        currency: 'Moeda',
        dark_mode: 'Modo escuro',
        notifications: 'Notificações',
        deposit: 'Depósito',
        withdraw: 'Sacar',
        balance: 'Saldo disponível',
    },
    Turkish: {
        home: 'Anasayfa',
        start: 'Başlat',
        record: 'Kayıt',
        dashboard: 'Panel',
        welcome: 'Tekrar hoşgeldiniz',
        wallet: 'Cüzdan',
        profile: 'Profil',
        support: 'Destek',
        settings: 'Ayarlar',
        language: 'Dil',
        currency: 'Para Birimi',
        dark_mode: 'Karanlık Mod',
        notifications: 'Bildirimler',
        deposit: 'Para Yatır',
        withdraw: 'Para Çek',
        balance: 'Kullanılabilir Bakiye',
    },
    Russian: {
        home: 'Главная',
        start: 'Начать',
        record: 'История',
        dashboard: 'Панель',
        welcome: 'С возвращением',
        wallet: 'Кошелек',
        profile: 'Профиль',
        support: 'Поддержка',
        settings: 'Настройки',
        language: 'Язык',
        currency: 'Валюта',
        dark_mode: 'Темная тема',
        notifications: 'Уведомления',
        deposit: 'Депозит',
        withdraw: 'Вывод',
        balance: 'Доступный баланс',
    },
    Hindi: {
        home: 'होम',
        start: 'शुरू करें',
        record: 'रिकॉर्ड',
        dashboard: 'डैशबोर्ड',
        welcome: 'वापसी पर स्वागत है',
        wallet: 'वॉलेट',
        profile: 'प्रोफ़ाइल',
        support: 'सहायता',
        settings: 'सेटअप',
        language: 'भाषा',
        currency: 'मुद्रा',
        dark_mode: 'डार्क मोड',
        notifications: 'सूचनाएं',
        deposit: 'जما करें',
        withdraw: 'نिकासी',
        balance: 'उपलब्ध शेष राशि',
    },
    Vietnamese: {
        home: 'Trang chủ',
        start: 'Bắt đầu',
        record: 'Lịch sử',
        dashboard: 'Bảng điều khiển',
        welcome: 'Chào mừng trở lại',
        wallet: 'Ví',
        profile: 'Hồ sơ',
        support: 'Hỗ trợ',
        settings: 'Cài đặt',
        language: 'Ngôn ngữ',
        currency: 'Tiền tệ',
        dark_mode: 'Chế độ tối',
        notifications: 'Thông báo',
        deposit: 'Nạp tiền',
        withdraw: 'Rút tiền',
        balance: 'Số dư khả dụng',
    }
};

interface LanguageContextType {
    language: LanguageCode;
    availableLanguages: LanguageCode[];
    setLanguage: (lang: LanguageCode) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
    language: 'English',
    availableLanguages: ['English'],
    setLanguage: () => { },
    t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

import { useSiteSettings } from './SettingsContext';

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const { profile } = useAuth();
    const { languages: backendLanguages } = useSiteSettings();
    const [language, setLanguage] = useState<LanguageCode>('English');
    const [availableLanguages, setAvailableLanguages] = useState<LanguageCode[]>(['English', 'Spanish', 'French', 'German', 'Chinese', 'Japanese', 'Arabic', 'Portuguese', 'Turkish', 'Russian', 'Hindi', 'Vietnamese']);

    useEffect(() => {
        if (backendLanguages && Array.isArray(backendLanguages)) {
            setAvailableLanguages(backendLanguages as LanguageCode[]);
        }
    }, [backendLanguages]);

    useEffect(() => {
        const savedLang = localStorage.getItem('language') as LanguageCode;
        if (savedLang && translations[savedLang]) {
            setLanguage(savedLang);
        } else if (profile?.language && translations[profile.language as LanguageCode]) {
            setLanguage(profile.language as LanguageCode);
        }
    }, [profile]);

    const handleSetLanguage = async (lang: LanguageCode) => {
        setLanguage(lang);
        localStorage.setItem('language', lang);

        if (profile?.id) {
            try {
                await supabase
                    .from('profiles')
                    .update({ language: lang })
                    .eq('id', profile.id);
            } catch (err) {
                console.error('Failed to persist language setting:', err);
            }
        }
    };

    const t = (key: string) => {
        return translations[language][key] || translations['English'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, availableLanguages, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}
